### ISSUE TITLE
Minor improvement to Fastlane's full_description.txt

### ISSUE THREAD

**Issue by IzzySoft** [Hamza417/Peristyle#1]
Could you please insert an empty line before the bullet-point list [here in your `full_description.txt`](https://github.com/Hamza417/Peristyle/blob/master/fastlane/metadata/android/en-US/full_description.txt#L1C1-L8C28)? That would make it possible to render it as Markdown, which would look much better – as you can [see here](https://apt.izzysoft.de/packages/app.simple.peri/) in about an hour from now :wink:

**Comment by Hamza417** [comment]
Done!, can you verify it?

**Comment by IzzySoft** [comment]
Wonderful, thanks – confirmed :smiley: Enabled that as well then to be checked when pulling updates. If you wish, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for your Readme to link to your app in my repo. People can use an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice to install your app from there and keep it updated.
