### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [Hamza417/Peristyle#100]
Please do not forget increasing `versionCode` when making a new release :wink: Updater here today reported:

    Binary files /web/ftp/repo/fdroid/repo/app.simple.peri_330.apk and /web/ftp/repo/fdroid/repo/app.simple.peri_3.3.1.apk differ

which means, 3.3.1 had the same `versionCode` (330) as 3.3.0 – so whoever has 3.3.0 installed, won't get an offer to update to 3.3.1…

**Comment by Hamza417** [comment]
It's an overlook from my side, I [corrected the error](https://github.com/Hamza417/Peristyle/commit/a4085c70ff37dc6a27e5245bae6e4150aa30b8f9) and will upload the rebuild again.

**Comment by IzzySoft** [comment]
Thanks! But please do not replace what already has been distributed (especially as your app has reproducible builds enabled: this will break reproducibility). That APK will not reach IzzyOnDroid as the tag was already pulled. Better make a maintenance release (or in cases like this, just roll the fix out when the next release is due).

But good to see it fixed, thanks!

**Comment by Hamza417** [comment]
Thanks for letting me know that.
