### ISSUE TITLE
Peristyle app crash

### ISSUE THREAD

**Issue by soberafmf1** [Hamza417/Peristyle#104]
Peristyle app will not open past the initial screen granting permissions and such.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Warning:** Any bug reports withut proper steps to reporduce the issue and relevent info will be closed/ignored.

**Comment by Hamza417** [comment]
It's a known issue and f[ixed already yesterday](https://github.com/Hamza417/Peristyle/commit/f8c5df28c95ff26f676ab351d5dfe4f711926553), for the time being you can try staying on the Setup screen for 30 seconds and then press the continue button. This should help you get in the app.

**Comment by Hamza417** [comment]
[Peristyle_(v4.0.0).zip](https://github.com/user-attachments/files/17528872/Peristyle_.v4.0.0.zip) you can via pre-release file for the time being if you want the apk with the fix.

**Comment by Hamza417** [comment]
Is it fixed?
