### ISSUE TITLE
memory card is not showing

### ISSUE THREAD

**Issue by ansarimohammed422** [Hamza417/Peristyle#106]
**Describe the bug**
Memory card is not showing in folder selection in new version 5.0.0

**Comment by Hamza417** [comment]
It's not a bug, Android doesn't support memory cards, there is no way to fetch that info from the OS.

**Comment by Hamza417** [comment]
I'd say move your wallpapers to internal storage, SAF was used for the very same reason, but it had so many other problems and was bound to be replaced sooner or later. If using internal storage isn't an option, you can downgrade to the previous version that works on the SAF. I'll add this warning in the release notes of the app.

**Comment by ansarimohammed422** [comment]
Is'nt there any way around other than downgrading

**Comment by Hamza417** [comment]
You can manually edit the paths in the app's preference file, but that requires root.

**Comment by ansarimohammed422** [comment]
I cant shift my wallpaper directory to internal storage i have 10 to 14 gb of wallpapers

Thats why i am asking

**Comment by Hamza417** [comment]
I took the code from Inure to add the support for it, it's there now in the folder picker.
