### ISSUE TITLE
Home screen wallpaper doesn't change anymore

### ISSUE THREAD

**Issue by rigerc** [Hamza417/Peristyle#108]
**Describe the bug**
Ever since updating to 5.0 and reconfiguring the home screen wallpaper doesn't change automatically anymore (or when triggered by the widget). Lockscreen works fine 

**To Reproduce**
Use v5 and separate configurations for home and lock screen 

**Smartphone (please complete the following information):**
 - Device: pixel 7a
 - OS: Android 15
 - Version 5.0

**Comment by Hamza417** [comment]
@rigerc

**Comment by Hamza417** [comment]
I just checked, it's working fine.
![Screenshot_2024-10-31-15-09-12-561_com mi android globallauncher](https://github.com/user-attachments/assets/e2ba281b-6f88-4be8-a408-779b3d6d1a34)

**Comment by rigerc** [comment]
I deleted storage & cache and set everything up again and it works now!
