### ISSUE TITLE
Desync between Home and Lock screens while both should be changed to the same wallpaper

### ISSUE THREAD

**Issue by borisfaure** [Hamza417/Peristyle#109]
**Describe the bug**
I'm using the app to change wallpapers from a defined directory on both the home and lock screens.
It changes the wallpaper but after some point, the one in the lock screen and in the home screen are different.

**To Reproduce**
1. Wait a few wallpaper iterations
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel7a
 - OS: Android15
 - Version: 5.0

**Additional context**
I cleared App Data + Cache and had to reconfigure the app. Still after some point, the screens have different wallpaper.

**Comment by Hamza417** [comment]
[app-prod-release.zip](https://github.com/user-attachments/files/17644513/app-prod-release.zip)

I have rewritten everything and probably fixed the issue, you can update and continue using the app and let me know if you face any odd problems.

**Comment by borisfaure** [comment]
Sadly, the app crashes when changing wallpapers.

**Comment by Hamza417** [comment]
> Sadly, the app crashes when changing wallpapers.

It shouldn't, do you have the logs?

**Comment by Hamza417** [comment]
[auto_wallpaper_test_2.zip](https://github.com/user-attachments/files/17649598/auto_wallpaper_test_2.zip)

You can install this, I have fixed any potential issues I could find.

**Comment by borisfaure** [comment]
I no longer crashes but it does not change wallpapers. How do I get logs?

**Comment by Hamza417** [comment]
> I no longer crashes but it does not change wallpapers. How do I get logs?

I am currently running it, and it's changing fine. Can you try recreating the wallpaper database and run it again?

**Comment by borisfaure** [comment]
I've tried emptying the cache, recreating the database, uninstalling, rebooting... 
Some older versions used to work just fine.
The quick settings button to change wallpapers does not work anymore.
How do I get logs of the app?

**Comment by Hamza417** [comment]
Can you show me your auto wallpaper settings so that I can replicate it in my device before doing anything else?

**Comment by borisfaure** [comment]
The new interface is not very practical for this since the value selected are not displayed directly (same on wizard: unclear which permissions are missing).

-------- Original Message --------

**Comment by borisfaure** [comment]
![Screenshot_20241106-225849](https://github.com/user-attachments/assets/ae29eda4-d19e-48be-aff2-db1025f28cf7)

**Comment by Hamza417** [comment]
Why is this looking like this?

**Comment by Hamza417** [comment]
![Screenshot_2024-11-07-08-42-11-639_com mi android globallauncher](https://github.com/user-attachments/assets/c51c3e2f-4ae5-47bc-bb7f-ae16c2ec5aad)

I've tried it and wallpapers are still setting fine.

**Comment by Hamza417** [comment]
I ran all the checks and auto wallpaper seems to be working flawlessly now. I'll upload a release soon after another round of testing, if then you face any problems you can open a new issue regarding that.

**Comment by Hamza417** [comment]
I have been testing it for the past few days and found the source of the issue and have already fixed it. I'll publish a release with the fix soon.
