### ISSUE TITLE
Peristyle's data folder grows exponentially with each use.

### ISSUE THREAD

**Issue by Smutley** [Hamza417/Peristyle#110]
**Describe the bug**
 Every time you add a pic, or change a wallpaper, or delete a pic etc., Peristyles data folder grows exponentially. I noticed my free space was decreasing on my phone, and could not figure out why. Finally, I decided to check Peristyle's data folder - it had ballooned to over 1G.

I deleted the data, and reconfigured Peristyle. Data folder was about 18MB; added a new wallpaper pic, and data folder was now 24 MB .... you can figure out the rest. This has nothing to to with the size of my designated wallpaper folder. Note: With regular use it only takes about a week for the data folder to hit 500MB. It happens on my 3 devices that I use Peristyle on.

**To Reproduce**
1. add a  pic
2. edit a pic
3. change a pic
4. delete a pic etc

**Expected behavior**
Data folder stays within the realm of reality. It should not grow simply by adding, removing, or editing pics.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Android 13, Android 11, Lineage OS 14
 - Browser Firefox
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: Xiaomi Red Mi Note 11, Samsung Galaxy Tab, Pixel 8
 - OS: EvolutionX 13, Android 11, Lineage OS 14
 - Browser Firefox latest stable

**Additional context**

**Warning:** Any bug reports without proper steps to reproduce the issue and relevant info will be closed/ignored.

**Comment by Hamza417** [comment]
It's not a bug, it's designed to cache everything. There's a built in clear cache feature which you can use to clear the arbitrary cached data and free up the space but it'll be rebuilt again. I'm guessing you've a library over a few hundreds in size that'd be the reason why your cache is built up so quickly.

![Screenshot_2024-11-08-01-35-25-209_app simple peri](https://github.com/user-attachments/assets/02b0e044-a2b4-4fed-ad7a-9591011d4d01)

**Comment by Smutley** [comment]
It is not the cache folder. It is the data folder. Using the built in "clear cache" feature did nothing to change the size of the data folder. And, it happens whether there are 5 pics or 500+ pics. The issue is use of the database, not the number of photos or the size of the them. BTW, I have 117 pics taking up 94 MB.  There is no way the database should grow to over 1 GB in a matter of weeks no matter what is happening, especially "caching" the pics.

If this is how peristyle is going to work, then I will not use it. It also has the same issues it has had from the beginning - not being able to see new pics consistently, not displaying new pics even though it knows they are there, not recognizing changes to pics, taking sometime days for changes to be recognized, and so on.

 It is a kinda cool app, but unlike Positional, or Inure, it has persistent database bugs that are not being acknowledged or addressed and make using it more and more of a pain. Add to this the bizarre interface change, and it is no longer a novel new way of displaying and applying local wallpapers. It used to be fun to use - now it is not. Uninstalling.

**Comment by Hamza417** [comment]
I'm not here to listen to your whining, lol... go away.
