### ISSUE TITLE
[Error] Still not setting same wallpaper for home and lock

### ISSUE THREAD

**Issue by svendsvin** [Hamza417/Peristyle#113]
### Confirmation

- [X] I have read the [Code of Conduct](https://github.com/Hamza417/Peristyle/blob/master/CODE_OF_CONDUCT.md)
- [X] I have searched the existing issues

### Error Description

Still not setting same wallpaper for home and lock

### Steps to Reproduce

??

### Expected Behavior

same wallpaper on home and lock screen 

### Device Information

Motorola g54 - android 14

### Sufficiency Confirmation

- [X] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Hamza417** [comment]
Could you show me your auto wallpaper configuration?

**Comment by svendsvin** [comment]
I tried to enable Pick in Linear Order. That didn't change anything; still different wallpapers.

Thanks for a great app 👍👍👍

________________________________
Fra: Hamza Rizwan ***@***.***>
Sendt: 16. november 2024 06:26
Til: Hamza417/Peristyle ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [Hamza417/Peristyle] [Error] Still not setting same wallpaper for home and lock (Issue #113)


Could you show me your auto wallpaper configuration?

**Comment by Hamza417** [comment]
Can you show me the complete settings? I'd need to check if all the conditions are met before suggesting a fix or try to find the cause of the problem.. :)

**Comment by svendsvin** [comment]
Sure. Attached.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hamza417** [comment]
I couldn't find it, I think GitHub doesn't support attachment via emails so you may have to manually upload it here.

**Comment by svendsvin** [comment]
I think it's bc I sent from my phone.

________________________________
Fra: Hamza Rizwan ***@***.***>
Sendt: 17. november 2024 07:08
Til: Hamza417/Peristyle ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [Hamza417/Peristyle] [Error] Still not setting same wallpaper for home and lock (Issue #113)


I couldn't find it, I think GitHub doesn't support attachment via emails so you may have to manually upload it here.

**Comment by Hamza417** [comment]
I'd suggest to reset all the settings in the Auto Wallpaper especially change some folders or tags and then set it back again, if you've specific folders or tags set for each screens I'd say reset them like change them to other and then change it back and then try again. Keep the linear wallpaper toggled.

**Comment by svendsvin** [comment]
I didn't know how to reset settings in the Auto Wallpaper, so I cleared storage/user data. That worked! I now see the same wallpaper in both screens. A minor thing, and not a problem for me, but in the overview when you open the app I still see two different wallpapers. Attached.
________________________________
Fra: Hamza Rizwan ***@***.***>
Sendt: 17. november 2024 09:00
Til: Hamza417/Peristyle ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [Hamza417/Peristyle] [Error] Still not setting same wallpaper for home and lock (Issue #113)


I'd suggest to reset all the settings in the Auto Wallpaper especially change some folders or tags and then set it back again, if you've specific folders or tags set for each screens I'd say reset them like change them to other and then change it back and then try again. Keep the linear wallpaper toggled.

**Comment by Hamza417** [comment]
> but in the overview when you open the app I still see two different wallpapers.

It's a bug in the framework, sometimes it returns old wallpapers for lock screen. I am still looking for a fix for that. Also, I have added random wallpapers slideshow in the home panel so it could be that, it automatically changes every 15 seconds. I am glad it works for you now.
