### ISSUE TITLE
[Bug] Folder selection not possible

### ISSUE THREAD

**Issue by adamindo** [Hamza417/Peristyle#114]
### Confirmation

- [X] I have read the [Code of Conduct](https://github.com/Hamza417/Peristyle/blob/master/CODE_OF_CONDUCT.md)
- [X] I have searched the existing issues

### Bug Description

The Folder selection screen is empty after update to v6.0.0

### Steps to Reproduce

During Setup (after update or fresh installation) open the folder selection.
The screen ist quiet empty, beside some buttons (cancel, select, and SD card).
/storage/emulated/0 is preselected an cannot be changed.

Trying to add/select a folder arfterward (via button instead of the setup screen) dies cause the same issue.

### Expected Behavior

It is possible to select one or more directories as a source for pictures

### Screenshots

![Screenshot_20241118-174331_Peristyle](https://github.com/user-attachments/assets/b2f489c4-9d14-423a-9f75-0c3170024415)

### Device Information

Android Smartphone Shift6mq with ShiftOS based in Android 10 without Google services

### Sufficiency Confirmation

- [X] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Hamza417** [comment]
Was the storage permission granted to the app before opening folder selection?

**Comment by adamindo** [comment]
Yes, the APP was working fine before the update. The permission was and is granted.

To make it sure, I unstalled the APP again, reinstalled it and granted the access before trying to select a folder. With the same result.

Am 18. November 2024 18:36:49 MEZ schrieb Hamza Rizwan ***@***.***>:

**Comment by Hamza417** [comment]
I checked and the folders are showing in my device. I also haven't changed anything in the folders screen since it was added in the app so it shouldn't just randomly break. Could you downgrade to the previous working version and let me know if it's working? You can start by [v5.2.0](https://github.com/Hamza417/Peristyle/releases/tag/v5.2.0).

**Comment by adamindo** [comment]
Okay, so I tested some stuff. You are right, the folder screen is not working for me in older versions as well.

I can set up the APP with the legacy UI. Afterwards I can use the APP in older versions.
With the update to v6.0.0 the APP is not working anymore and the following exception is thrown:


java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt.random(SourceFile:36)
	at app.simple.peri.services.AutoWallpaperService.getHomeScreenWallpaper(SourceFile:251)
	at app.simple.peri.services.AutoWallpaperService.access$setHomeScreenWallpaper(SourceFile:1)
	at app.simple.peri.abstraction.AbstractComposeAutoWallpaperService$setComposeWallpaper$1.invokeSuspend(SourceFile:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)


But I can use the APP in v6.0.0 when I stay with the legacy UI.



Am 18. November 2024 20:49:50 MEZ schrieb Hamza Rizwan ***@***.***>:

**Comment by Hamza417** [comment]
> java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt.random(SourceFile:36)
	at app.simple.peri.services.AutoWallpaperService.getHomeScreenWallpaper(SourceFile:251)
	at app.simple.peri.services.AutoWallpaperService.access$setHomeScreenWallpaper(SourceFile:1)
	at app.simple.peri.abstraction.AbstractComposeAutoWallpaperService$setComposeWallpaper$1.invokeSuspend(SourceFile:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)

It occurred because there wasn't any file added in the database, it's a side effect of the current issue. 

Did something change in your device recently or a new mod or anything that could affect the other apps? An AppOps controller can do something like that.

**Comment by adamindo** [comment]
Hello Hamza, sorry, I couldn't answer sooner.
Thank you for your quick responses and your efforts.

I'm currently running v4.0.0, which works fine for me.
Here I can use the setup screen an select my background folder. The folder Selektion screen looks like that.
![Screenshot_20241120-214613_Peristyle](https://github.com/user-attachments/assets/3e498e8f-39f5-415f-9d68-0c0cdc8f5bd0)

When I upgrade to 5.0.0 some issues come up and I can't use the folder selection screen anymore. Now I need to switch to the legacy UI. I don't get exception messages, but the automatic background switch becomes unreliable.

When I upgrade to 6.0.0 additionally the exception messages pop up as long as I do not switch to the legacy UI. But even with the legacy UI I can't set up the APP correctly and the automatic background switch is not working properly.

**Comment by Hamza417** [comment]
> But even with the legacy UI I can't set up the APP correctly and the automatic background switch is not working properly.

You may need to clear your app data before switching to the legacy UI.

> When I upgrade to 5.0.0 some issues come up and I can't use the folder selection screen anymore. Now I need to switch to the legacy UI. I don't get exception messages, but the automatic background switch becomes unreliable.

Yes, [I changed the whole database framework in the v5.0.0 and moved away from Scoped Storage](https://github.com/Hamza417/Peristyle/releases/tag/v5.0.0). The current implementation should work, but for some reason it's not working on your device. Could you upgrade to the latest version and generated logs of the app and send me the file? I'd recommend the complete system logs during the setup of the Peristyle app to see if something in your device blocking the app's access to the file system.

You can use this command to create the logs of the app: `adb logcat -c && adb logcat > logs.txt`

**Comment by adamindo** [comment]
Can I send them to you on a less public way?

**Comment by Hamza417** [comment]
You can upload here.

**Comment by adamindo** [comment]
I have created two log files, one for an installation of 4.0.0 and update to 6.0.0 and wone with a new installation of 6.0.0.
[logsUpdate.txt](https://github.com/user-attachments/files/17867417/logsUpdate.txt)
[logsInstall.txt](https://github.com/user-attachments/files/17867418/logsInstall.txt)

**Comment by adamindo** [comment]
Thank you very much

**Comment by Hamza417** [comment]
![image](https://github.com/user-attachments/assets/95bd1bad-1e46-44ca-98f2-3c1ee71fc53e)

I have managed to reproduce this problem in my emulator. I am working on a possible fixes now.

**Comment by adamindo** [comment]
That looks awsome, thank you very much.
I'm able to select the folder and I'm running the APP now for some hours and it runs stable doing it's job. Great work.

**Comment by Hamza417** [comment]
I'm glad :)
It's a release build so you can continue using the same app. I'll publish a release soon for everyone else.
