### ISSUE TITLE
[Feature Request] Mass Tag Adding

### ISSUE THREAD

**Issue by frfeed123** [Hamza417/Peristyle#117]
### Confirmation

- [X] I have read the [Code of Conduct](https://github.com/Hamza417/Peristyle/blob/master/CODE_OF_CONDUCT.md)
- [X] I have searched the existing issues

### Feature Description

A tool/button to select a mass of pictures to add tags to.

### Describe the Solution

After clicking the button you could via checkmarks on all pictures selceted them and then after clicking a checkmark would ask what tags to apply to them.

### Describe Alternatives

Another addon would be the ability to pull from one picture and all pictures since that one would be selected (like in most gallerys as an example samsungs gallery app).

### Sufficiency Confirmation

- [X] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Hamza417** [comment]
Moving and Adding Tags for multiple selected wallpapers is already a work in progress at the moment.

**Comment by frfeed123** [comment]
I edited the comment a bit read alternatives again pls

**Comment by Hamza417** [comment]
> Another addon would be the ability to pull from one picture and all pictures since that one would be selected (like in most gallerys as an example samsungs gallery app).

I don't have a samsung device, could you elaborate this part more?

**Comment by frfeed123** [comment]
I will make an example screen record a second please.

**Comment by frfeed123** [comment]
https://github.com/user-attachments/assets/e6d5186b-3f9d-46db-a963-294520a25f7c

Here an example.

**Comment by frfeed123** [comment]
Please message me after you watched it so I can delete it.
Just noticed that I accidentally showed something nsfw on the left hand side.

**Comment by Hamza417** [comment]
Yeah, I think something like this can be done as well. It'd be best to open a separate issue for this feature.

**Comment by frfeed123** [comment]
And even better not to accidentally show nsfw in the preview video XD

**Comment by Hamza417** [comment]
It's added now, you can now add tags to multiple selected wallpapers at once from the selection menu.

**Comment by frfeed123** [comment]
> It's added now, you can now add tags to multiple selected wallpapers at once from the selection menu.

How do i access said menu cuz i can't find it.
