### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Hamza417/Peristyle#12]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6007094480#L591

please be consistent in your tag naming, be it with `v` or without `v`

**Comment by Hamza417** [comment]
It was supposed to start with v, I forgot writing it this time. Should I publish the release again?

**Comment by licaon-kter** [comment]
yes, you can retag

**Comment by Hamza417** [comment]
Done, it should work now.

**Comment by licaon-kter** [comment]
thanks
