### ISSUE TITLE
Separate folders and controls for home and lock screens.

### ISSUE THREAD

**Issue by ghost** [Hamza417/Peristyle#14]
Second part of #4 - "and separate controls for the lock screen and home screen (different folders and control options).".

Egsample: use one album for lock screen and another album for home screen.

Thanks :)

**Comment by Warden20** [comment]
Maybe a favorites folder could be an option too

**Comment by Hamza417** [comment]
It has been added [in this commit](https://github.com/Hamza417/Peristyle/commit/79ba45be1639ce19369844e14d6092501e4e04a9), however a separate folder is not planned yet and reserved for future.

**Comment by ViktorKahu** [comment]
I appreciate the work, but how/why is this closed as completed?

As far as I can see, I still can not select different folders to use for lock screen and homescreen with the auto-switcher, which was the whole point of raising this issue.

Am I doing something wrong, or was the request not understood correctly?

**Comment by Hamza417** [comment]
I've checked and decided not to go with it, Having multiple directories requires a totally different approach in Android and won't be worked on.

**Comment by Hamza417** [comment]
It has been added in the release v2.02_beta.
