### ISSUE TITLE
The app doesn't change wallpaper in the background

### ISSUE THREAD

**Issue by Bhambya** [Hamza417/Peristyle#17]
I think the app needs to use a Foreground service with ongoing notification. Otherwise the AutoWallpaperService just closes in the background.

**Comment by Hamza417** [comment]
@Bhambya You may need to turn off the battery optimisation for Peristyle for it to work. The app already uses foreground services but some devices may prevent it from starting in the background.

**Comment by Bhambya** [comment]
Thank you. I saw the code and it uses inexact alarms. They are inherently not accurate. I was thinking about a constantly running background service but ofcourse that will consume more battery. Closing the ticket for now. Thanks!
