### ISSUE TITLE
[Bug] can't load wallpapers when open app

### ISSUE THREAD

**Issue by mojienjoyment** [Hamza417/Peristyle#19]
I can't find any wallpaper when open app. I use vpn also, but didn't worked. I tried to change directory but same. I find out that when I go to app info and "mobile data and wifi" section, I cant enable data access to this app. Maybe permission problem?
Screenshot:
![Screenshot_20240227-221619_Settings](https://github.com/Hamza417/Peristyle/assets/68327458/3299c717-43cc-4c55-8f13-6b86426d9ad0)
 Android 14 crdroid 10.2 poco x3pro

**Comment by Hamza417** [comment]
It's an offline wallpaper manager app, you'll have to select a directory where you store your wallpapers to have them show in the app.

**Comment by mojienjoyment** [comment]
> It's an offline wallpaper manager app, you'll have to select a directory where you store your wallpapers to have them show in the app.

Wow! :) I didn't kow that! Thx for ur reply
