### ISSUE TITLE
Load from sub-directories

### ISSUE THREAD

**Issue by tasmo** [Hamza417/Peristyle#21]
An option to load wallpapers from child folders of the chosen wallpaper directory would be great.

**Comment by Hamza417** [comment]
Peristyle [supports one level subdirectory tree](https://github.com/Hamza417/Peristyle/blob/a994127d34afc251a24a02e38be627bcb4f644d7/app/src/main/java/app/simple/peri/viewmodels/WallpaperViewModel.kt#L137-L149), does your wallpaper directory have deeper branches than that?
