### ISSUE TITLE
Auto save the filters

### ISSUE THREAD

**Issue by MuhammadAliAsgar** [Hamza417/Peristyle#24]
Imagine I've just set 'X' pic as wallpaper doing some filters.
Next time, when I go and open 'Y' pic, I see the filters are reset !
So, what I want is an option to have my own preferred filter as default ...

**Comment by Hamza417** [comment]
It's intended to adjust the wallpaper colors before applying it, it's not meant to be a consistent filter style.

**Comment by Hamza417** [comment]
I have added the [option to save effects in the Wallpaper screen in the new interface of the app](https://github.com/Hamza417/Peristyle/commit/9fe85b38ae2c0427a483e5ab6e3a0780b8308ef0). You can see the [screenshot here](https://github.com/Hamza417/Peristyle/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/11.png).
