### ISSUE TITLE
feature req: manual cycle to next auto wallpaper

### ISSUE THREAD

**Issue by nutpantz** [Hamza417/Peristyle#25]
sometimes when on "auto" i have a wallpaper that i only like once in a while and would like to switch to the next wall paper in sequence.  
 
it would be nice if i could manually switch to the next wallpaper on demand.  
maybe with a a widget ( with options like, last, next, random)
or just double tap the screen to switch to the next wallpaper in sequence.
( or some other simple method)

**Comment by Hamza417** [comment]
@nutpantz There already is a widget for this, please read the change logs and description.
