### ISSUE TITLE
Fit inside screen option 

### ISSUE THREAD

**Issue by Turhvjbufv** [Hamza417/Peristyle#27]

**Comment by Hamza417** [comment]
@Turhvjbufv Could you elaborate what you mean by this?

**Comment by Hamza417** [comment]
Wallpapers are supposed to fill the screen.

**Comment by Hamza417** [comment]
I've added an option, tapping the image will now switch between the alternate scales (the default one and the one you mentioned). This is only available in the main wallpaper screen.
