### ISSUE TITLE
[Feature Request] An option to exclude loading wallpapers from sub-folders

### ISSUE THREAD

**Issue by Username1-a** [Hamza417/Peristyle#29]
Some versions ago, there was an inclusion of sub-folders introduced – would be great if it was optional for more control over wallpaper management

**Comment by Hamza417** [comment]
It was a bug actually that the subdirectory wasn't read properly and [was fixed](https://github.com/Hamza417/Peristyle/issues/21). It's an intended behavior.

**Comment by Hamza417** [comment]
The app was designed to read a single directory and show all wallpapers to a single place. Your problem can be easily solved by storing your wallpapers in a different directory where there isn't other photos you don't want to be listed in the app.

**Comment by Hamza417** [comment]
It's added now :)
