### ISSUE TITLE
Dangerous gestures

### ISSUE THREAD

**Issue by ViktorKahu** [Hamza417/Peristyle#3]
A careless swipe on the image to the left or right, permanently deletes the wallpaper with no warning or ability to undo or recover.

I don't even know which images of many were deleted out of my large collection.

Please fix before other unsuspecting users permanently lose data.

Many thanks.

**Comment by Hamza417** [comment]
- Added a popup for swipe delete confirmation (https://github.com/Hamza417/Peristyle/issues/3)
- Added option to completely disable the swipe to delete (https://github.com/Hamza417/Peristyle/issues/3)

These two features should help now :)
