### ISSUE TITLE
Wallpaper goes from high res to low res when you open preview

### ISSUE THREAD

**Issue by vcsolanki** [Hamza417/Peristyle#30]
I don't know what is happening, I have downloaded 4k wallpapers, when I open them I see high resolution but it quickly turns into low resolution wallpaper.

Like app is lowering quality of wallpaper immediately when preview is opened.

You can see it here: https://drive.google.com/file/d/1CKVxsNvWXbx7RMssyDtQR5UxADGCfIHW/view?usp=drivesdk

**Comment by Hamza417** [comment]
Thanks for the report, it was a blurring issue and it's fixed now.
