### ISSUE TITLE
Wallpaper switcher doesn't work

### ISSUE THREAD

**Issue by Banbury** [Hamza417/Peristyle#31]
Device: Samsung Galaxy A25
OS: Android 14

I have selected a folder for the wallpapers, activated wallpaper switching, and set the interval to 1 minute. The wallpaper is never changing, even if the app is running in the foreground, and the phone is not sleeping. I have turned off all energy optimizations for the app in the settings, but it doesn't make any difference.

Also the widget to switch wallpapers only works, if the app is open, which defeats the purpose of the widget.

I think a background service is needed to achieve the auto wallpaper switching.

**Comment by Hamza417** [comment]
It already uses background service, you need to disable battery optimizations for Peristyle for it to work.

**Comment by Hamza417** [comment]
Added a dialog to disable battery optimizations when auto wallpaper is enabled.
