### ISSUE TITLE
Error "radius < 1: 0" 

### ISSUE THREAD

**Issue by borisfaure** [Hamza417/Peristyle#32]
I'm trying to use version 1.40_beta but it fails setting a wallpaper as background with an error `radius < 1: 0`.
I've looked a bit at the code and it's related to blur even though the blur option is disabled.

**Comment by borisfaure** [comment]
Hi. I've updated to 1.41_beta but the issue is still present.

**Comment by Hamza417** [comment]
I caught the wrong exception, I'll publish a new release in a moment

**Comment by Hamza417** [comment]
I've updated the existing release, you can update now.

**Comment by borisfaure** [comment]
Thanks! It now works like a charm
