### ISSUE TITLE
Library stats not displaying expecting wallpapers size

### ISSUE THREAD

**Issue by borisfaure** [Hamza417/Peristyle#34]
When running the `Library stats` function, it says I have 0 `Fitting Wallpapers` and lots of `Excessive Wallpapers`.
`Insufficient Wallpapers` are indeed correct.
It would be great to know what is the expected size to have `Fitting Wallpapers`.

**Comment by Hamza417** [comment]
Fitting Wallpapers simply means the wallpapers that are exactly the resolution of your device. I haven't found the proper term for that yet.

**Comment by borisfaure** [comment]
When browsing the wallpapers, their size can be displayed and that's great to know.
I think my wallpapers are actually the `fitting` size, but since I can't see what the app expects, I don't know if I'm right

**Comment by Hamza417** [comment]
@borisfaure In the main list, insufficient wallpapers have a warning indicator, the excessive wallpapers are just to indicate the wasted details and space. I'll try to add better explanation for this in the app.

**Comment by borisfaure** [comment]
Most of my wallpapers are 1080 x 2400 pixels, which is supposed to be the size of the display, but they're not considered as `fitting`, that's why I'd like to know what is the expected size for Peristyle.

**Comment by Hamza417** [comment]
I checked and there was a bug, the returned value doesn't include the status bar height in the height.

**Comment by Hamza417** [comment]
It's fixed now
