### ISSUE TITLE
Use photos from different folders

### ISSUE THREAD

**Issue by ReKylee** [Hamza417/Peristyle#35]
This app would literally be perfect if only I could select individual pictures from different folders instead of having to create a new folder called Wallpapers, and copy the images there, costing in more storage space.
Maybe the database should have file and folder paths instead of one single folder.

**Comment by Hamza417** [comment]
I appreciate the idea, but It's only created to be a single directory based wallpaper manager, I do not have any plans and resources to extend it any further unless I need it to.
