### ISSUE TITLE
[Bug] Wrong Wallpaper Orientation

### ISSUE THREAD

**Issue by microbearsmb** [Hamza417/Peristyle#38]
First off, thank you so much @Hamza417 for this app!

I've had one problem that I can't seem to shake. It's fine when I do it manually, or enable wallpaper cropping, but when wallpapers are applied automatically as scrollable, most of my vertical aspect ratio wallpapers get turned sideways. Is this a user error on my end, or might this be a bug?

For reference, these photos are vertical by default - they appear correctly in another wallpaper app as well as in my gallery.

**Comment by Hamza417** [comment]
Could be a bug or device specific issue, or in some cases the wallpaper appears to be stretched out or set weirdly when wallpaper is set while the device is in landscape orientation, e.g. auto wallpaper ran while you were watching a movie.

**Comment by microbearsmb** [comment]
Could be device specific, but all the testing I did was in portrait mode, so I don't think landscape mode was the problem. And the images aren't distorted, just sideways - the sky is on the left instead of the top.

**Comment by Hamza417** [comment]
This seems like the EXIF data in the images are wrong or incorrect. Are these images manually captured and being used as a wallpaper?

**Comment by microbearsmb** [comment]
That's definitely possible. And yes, they are all from this devices OEM camera app

**Comment by Hamza417** [comment]
I think I've fixed the issue, could you run the test and let me know before I publish the release?

[app-prod-release.zip](https://github.com/Hamza417/Peristyle/files/15112905/app-prod-release.zip)

**Comment by microbearsmb** [comment]
Bingo! Thank you so much!
