### ISSUE TITLE
Wallpaper switcher

### ISSUE THREAD

**Issue by ViktorKahu** [Hamza417/Peristyle#4]
The next logical step would be to implement an automatic wallpaper switcher for intervals set by the user, and separate controls for the lock screen and home screen (different folders and control options).

Thanks.

**Comment by Hamza417** [comment]
It's added now in [v1.29_beta](https://github.com/Hamza417/Peristyle/releases/tag/v1.29_beta), it's still in alpha, so open any new issue for bug reports.
