### ISSUE TITLE
Widget Issue / Request

### ISSUE THREAD

**Issue by ImAgoodGirlSumtimz** [Hamza417/Peristyle#40]
First, I absolutely love this app! Thank you! 

Issue: The next wallpaper widget doesn't work very well. It sometimes takes up to 25 or 30 seconds to change the wallpaper, and sometimes it doesn't change it at all. Clearing the cache sometimes helps but not very well or always.

Request: can you also provide a clear/transparent version widget for the homepage?

I'm running Android 14 on a Google Pixel 6 Pro.
Thank you so much!

**Comment by Hamza417** [comment]
Peristyle only takes about less than 2 seconds to set the wallpaper when _Next Wallpaper_ is clicked, it's a flaw in Android, it takes up a lot of resources in Android to just change the wallpaper and it became even worse after the Monet theming was introduced. There's nothing can be done here.

**Comment by Hamza417** [comment]
I've added a transparent widget for the _Next Wallpaper_ widget. The wallpaper crashing error is from Android side, there's a workaround for that. either enable crop wallpaper or use smaller wallpaper sizes that fits your device, large bitmaps throws out of memory error in the wallpaper framework of Android. I hope this works.
