### ISSUE TITLE
show current wallpaper

### ISSUE THREAD

**Issue by wieczniezielony** [Hamza417/Peristyle#42]
It would be nice to have a button to display current wallpaper on the list.

**Comment by Hamza417** [comment]
Android doesn't support accessing wallpapers by user apps.

**Comment by Hamza417** [comment]
I checked and found out that it's possible to get the wallpaper but only with MANAGE_EXTERNAL_STORAGE permission. I'm not sure anyone will ever grant the app this permission but I think I can make some plans to add folder support and other things that may utilize this permission better and simultaneously support this as well.

**Comment by Hamza417** [comment]
I have added this in v1.52, check it and let me know.
