### ISSUE TITLE
Wallpaper going off of the screen

### ISSUE THREAD

**Issue by weiss1597** [Hamza417/Peristyle#47]
Noticed recently the wallpapers sometimes goes off of the screen, to the right, so a "blank" space fills the remaining area on the left, with auto change on.

on the attached image it's the worst so far, with only a little bit of the wallpaper being shown on the right, the option to crop wallpaper is on.
![Screenshot_20240524-053601_Gallery](https://github.com/Hamza417/Peristyle/assets/158379757/41a800de-403e-4fe3-a754-e3b94149b77d)

and to be fair, I've only noticed it after changing the OS of my phone recently, so it could be my system that's messing something, or I didn't update the app before, cause I've also tried with version 1.42, changed wallpapers for a while using the widget and this problem didn't seem to happen anymore.

**Comment by Hamza417** [comment]
I'm not sure why this is happening, what's your wallpaper size and resolution and was the device in rotated state when the wallpaper was set?

**Comment by weiss1597** [comment]
It happens with a just a few wallpapers, found them, isolated and kept changing between them on auto wallpaper, the same problem happens every time the exact same way with just those wallpapers

one of those is 1.3mb 864x1728, 2 other that are smaller seems to "slide" more

my phone is 1080x2400 
Poco F5, Android 14 on Crdroid ROM
Last I used the app it was stock MIUI A13

I have auto rotation disabled, device should be on portrait mode.

And disregard that about version 1.42, it happens on this version as well.

**Comment by weiss1597** [comment]
Oh I think I've found something.

just as I've commented on the other issue, the wallpaper is centralized but zoomed in
checked the sizes of all the 5 zoomed in wallpapers and they are all bigger than my resolution, stuff like 2000x4000 or more

checked size of the 6 wallpapers that slid off, they are all smaller, like 900x1800 or less
and confirmed, the smaller it is the more off it gets
the one with 600x900 is on 1/3 of of the screen
the one with 900x1800 is just a bit off

**Comment by Hamza417** [comment]
I think it's safe to say that your device OS may not be working properly with these resolutions.

**Comment by weiss1597** [comment]
this only happens in auto mode, they work fine when manually setting the wallpaper using the app, regardless if it's bigger or smaller resolution

**Comment by Hamza417** [comment]
Setting wallpapers from the app upscales/downscales the wallpapers to the device's resolution. Auto wallpaper doesn't do it, that's why you're seeing the difference. Try changing your device rom or check in another device, it'd be best to do that before moving onto fixing the problem.
