### ISSUE TITLE
wider wallpapers when cropped aren't centralized

### ISSUE THREAD

**Issue by weiss1597** [Hamza417/Peristyle#48]
I'm guessing that when cropping wide wallpapers they should be centralized, and unless it's my impression, the app does seem to do that, sometimes at least, and if it doesn't centralize, it would be a nice addition.

the full wallpaper
![Screenshot_20240524-052645_Peristyle](https://github.com/Hamza417/Peristyle/assets/158379757/34cde1c3-2bd9-4a03-b8a4-045887a495c5)

and here's how it ends up
![ResizedImage_2024-05-24_05-34-50_1340](https://github.com/Hamza417/Peristyle/assets/158379757/6345df00-5f50-42d0-a228-38b74e56775b)

the screenshots were taken on version 1.42, but this same behavior happens on the latest version, just that on the latest version they are sometimes sliding off of the screen as mentioned on #47

**Comment by Hamza417** [comment]
I just tested it, cropping is working fine in both app and auto wallpaper. Can you run the app in a different device and preferably a device with vanilla Android?

**Comment by Hamza417** [comment]
> cropping is working fine in both app and auto wallpaper

Meaning it's cropping the wallpaper from the center as intended. When cropping is disabled ot relies on system wallpaper manager to set the wallpaper as the device intends it to.

**Comment by weiss1597** [comment]
I might be able to test it on some other phone, but it may take a while before that.

And also I've found another few wallpapers were it correctly aligns on the center, but they end up zoomed in

left full wallpaper, middle how it should have been, right how it ended up
![ResizedImage_2024-05-24_07-22-53_2602](https://github.com/Hamza417/Peristyle/assets/158379757/ad2564dd-4d05-4f36-9aad-002441470001)
centralized but zoomed in, that on auto wallpaper with cropping activated.

**Comment by Hamza417** [comment]
There are settings for showing zoomed in wallpapers, or either the device shows zoomed wallpaper by default. This is not an issue with the app.

![Untitled](https://github.com/Hamza417/Peristyle/assets/23103729/ae2dcf9a-2640-4503-8299-66e5f9ce7648)

**Comment by weiss1597** [comment]
this in fact fix the "issue" mentioned on #49 

but the zoom in here is much bigger, I've found out that it does centralize the wallpaper on auto mode but only if the resolution is bigger than the display, and the bigger the wallpaper resolution the more it zoom in

that first one I've showed is smaller than the display
