### ISSUE TITLE
Cropping wallpapers don't consider status bar and navbar

### ISSUE THREAD

**Issue by weiss1597** [Hamza417/Peristyle#49]
When cropping wallpapers, even if the wallpaper matches the screen size, the portion of the image behind navbar and status bar are being cut out and the wallpaper ends up smaller then source image

before applying, as visible on screen
![Screenshot_20240524-051350_Peristyle](https://github.com/Hamza417/Peristyle/assets/158379757/d769f81e-93e7-407e-b959-90f6deba9e97)

after applying the wallpaper
![Screenshot_20240524-053607_Gallery](https://github.com/Hamza417/Peristyle/assets/158379757/6846d403-cc49-451f-aa96-88a09ad73318)

an easy way to verify this is using a screenshot of the wallpaper as a wallpaper

**Comment by Hamza417** [comment]
Generally, Android zooms in the current wallpaper a little bit to compensate for animations. This is an expected behaviour.

**Comment by Hamza417** [comment]
_[See here](https://github.com/Hamza417/Peristyle/issues/48#issuecomment-2129543301) for the responses._
