### ISSUE TITLE
Toggle wallpaper sequence and separate timers.

### ISSUE THREAD

**Issue by gaabster** [Hamza417/Peristyle#50]
Hello.
I don't know how are wallpapers applied atm, but is it possible to have a toggle so that wallpapers can be re-used and/or randomized? And maybe a toggle to set them in sequence without repetition?
And another thing would be to allow to set separate timers for home and lock screen.
Thank you.

**Comment by Hamza417** [comment]
> I don't know how are wallpapers applied atm, but is it possible to have a toggle so that wallpapers can be re-used and/or randomized? And maybe a toggle to set them in sequence without repetition?

Can you elaborate? Currently, the wallpaper is set randomly, two wallpapers may or may not repeat depending on how many files you currently have, the probability goes low with higher number of files.

> And another thing would be to allow to set separate timers for home and lock screen.

What do you mean by timer?

**Comment by gaabster** [comment]
I was thinking to simply have an option to turn off any probability of repeating a wallpaper until the app goes through every available file.

Timer was a poor choice to describe it. Frequency is better I think. It would make it possible to set different frequency for home and lock screen auto wallpaper.
Example:
Home screen every 1 hour.
Lock screen every 12 hours.

These are just some silly ideas tho, nothing important.
The app is great. Thanks.

**Comment by Hamza417** [comment]
> I was thinking to simply have an option to turn off any probability of repeating a wallpaper until the app goes through every available file.

More like a linear selection of wallpapers, it's doable.

> Timer was a poor choice to describe it. Frequency is better I think. It would make it possible to set different frequency for home and lock screen auto wallpaper.
Example:
Home screen every 1 hour.
Lock screens every 12 hours.

I do not have any plans to separate their processes, I'll think about it later.

**Comment by Hamza417** [comment]
I have added the option to set wallpapers linearly.

**Comment by Hamza417** [comment]
I am currently planning adding multiple folders support in the app, and this could also introduce the opportunity to implement different delay controls for different screens. I'll keep this issue open, and you may expect updates here once I begin developing the multiple folder feature.
