### ISSUE TITLE
Homescreen blur on automatic wallpaper chane

### ISSUE THREAD

**Issue by yongkuk** [Hamza417/Peristyle#53]
Hi, thanks for such a useful app!

I'd love to have an option to apply blur on the homescreen when I choose automatic wallpaper change, so that a busy wallpaper can be viewed as it is in the lockscreen while not interfering with widgets and icon labels in the homescreen. (Similar to iOS wallpaper settings!)

I see that there is an option for blur in the wallpaper set screen, but it's missing in the automatic wallpaper change.

Thanks again for such a clean and simple yet useful app.

**Comment by Hamza417** [comment]
It's added now!!

**Comment by GabriFrz** [comment]
Hi, how do you set the home screen wallpaper to automatically blur?

**Comment by Hamza417** [comment]
> Hi, how do you set the home screen wallpaper to automatically blur?

It's the [second bottom at the bottom](https://github.com/Hamza417/Peristyle/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/01.png), there you will find the settings.

**Comment by GabriFrz** [comment]
Yes, though I mean blur only the home screen wallpaper while the lock screen one is fully visible, As of now it blur both of them. I tried the separate home screen wallpaper for home screen, the problem is that doing so it picks a different wallpaper for the home screen.
