### ISSUE TITLE
.nomedia included as wallpaper

### ISSUE THREAD

**Issue by CaptainLexington** [Hamza417/Peristyle#56]
When the app creates a .nomedia file, it is shown as a blank image on the wallpaper grid, and will be set as a wallpaper in auto mode. My Pixel 6 displays the system default wallpaper when this happens.

**Comment by Hamza417** [comment]
I have fixed the issue and added a database sanitizer as well. This should solve your issue.

**Comment by CaptainLexington** [comment]
Perfect! I just pulled the update and it works.
