### ISSUE TITLE
[Feature Request] Depth wallpapers?

### ISSUE THREAD

**Issue by xplshn** [Hamza417/Peristyle#58]
Depth wallpapers could be added like this:
 1. Allow adding a clock over the user-selected wallpaper. Set that as live-wallpaper
 2. Tell the user to disable his screenlock clock, in case his device allows it. (Many custom roms will let you do this)
 3. Let the user select a "subject image", which will be above the clock in the live-wallpaper.
 
 Thanks! Awesome project!

**Comment by Hamza417** [comment]
Peristyle is wallpaper library manager app, your request should align more with a dynamic live wallpaper or something of that nature.
