### ISSUE TITLE
Lowering the filename position to reduce clutter.

### ISSUE THREAD

**Issue by rickdtc** [Hamza417/Peristyle#6]
It would be great the file name position lowered from this : 

![1000106323 1](https://github.com/Hamza417/Peristyle/assets/74096544/45042241-6323-4da0-b5ce-71f29c61108e)

to this : 

![Group 1](https://github.com/Hamza417/Peristyle/assets/74096544/4f2fd6ef-baa4-4df3-a360-af066c572244)

Plus an option to fully remove the file name would be great too.

I feel like this has been thought of but not implemented yet, so is there like a todo I missed, which I can see to prevent creation of redundant issues?

**Comment by Hamza417** [comment]
Done!, you'll be able to see the fix in the next update

> Plus an option to fully remove the file name would be great too.

It's there already in the app settings.

**Comment by rickdtc** [comment]
> It's already there in the app settings.

Oh, sorry must have overlooked then, also, thanks!

On a side note, is it known that the icons on the settings page don't adapt with i.e turn lighter on dark mode, if not, should open a new issue?

**Comment by Hamza417** [comment]
> On a side note, is it known that the icons on the settings page don't adapt with i.e turn lighter on dark mode.

No, I didn't know about this, I'm working on it at them moment

> if not, should open a new issue?

You should open an issue regardless of anything, it's a good practice and open multiple issues for different problems.. :)

**Comment by rickdtc** [comment]
> You should open an issue regardless of anything, it's a good practice and open multiple issues for different problems… :)

Alright, just opened #7 👍
