### ISSUE TITLE
FR: Custom cropping area

### ISSUE THREAD

**Issue by mihawk90** [Hamza417/Peristyle#67]
Currently - as far as I can tell after first use - it seems to be only possible to either use a cropped image based on the currently visible part of the image, or use an entire uncropped image as is.

The former disables wallpaper scrolling because it of course fits the screen 1:1, the latter results in very wide swings for larger images (or even standard 16:9 aspect ratio), possibly with not much to show on every screen or characters in the image being cropped off.

It would be nice to be able to define a custom cropping area so that one could crop to for example a 1:1 aspect ratio area within the image, which would result in much less of a swing when scrolling the wallpaper.

**Comment by Hamza417** [comment]
Is it aspect ratio based cropping?
