### ISSUE TITLE
App Crashes When Assigning Wallpaper from "Open With..."

### ISSUE THREAD

**Issue by CaptainLexington** [Hamza417/Peristyle#69]
Steps To Reproduce
- I download some wallpaper and open it in my File Browser.
![Screenshot_20240901-143204.png](https://github.com/user-attachments/assets/0bf3d4fc-d0a0-4bbe-9c6a-2a1ee4c09626)

-  Open with Peristyle
![Screenshot_20240901-143152.png](https://github.com/user-attachments/assets/8a9c1e10-a3ba-4ff6-aa78-68bdc4d8a9ce)

- Arrange like you want and tap the set background button
![Screenshot_20240901-143213.png](https://github.com/user-attachments/assets/0672c122-d835-4904-8f9e-23303ef09a55)

- Crash at least 90% of the time 
![Screenshot_20240901-143217.png](https://github.com/user-attachments/assets/43e335b0-9dc3-4dec-a0db-325e763b6394)

Non-determinisic, it eventually succeeds.

Pixel 6. Peristyle 1.52_beta installed from IzzyOnDroid repo.

**Comment by Hamza417** [comment]
Fixed..
