### ISSUE TITLE
Icons don't adapt with dark mode.

### ISSUE THREAD

**Issue by rickdtc** [Hamza417/Peristyle#7]
Visual bug, icons don't adapt with dark mode i.e don't turn lighter on dark mode  :

![Frame 1 (12)](https://github.com/Hamza417/Peristyle/assets/74096544/ac8c45a2-9785-4649-9f76-c55a5179dce7)

Also, the icon pngs here don't change their background to dark too : 

![1000106346 1](https://github.com/Hamza417/Peristyle/assets/74096544/1350201e-fc23-4f8d-862a-d0561002eda8)

**Comment by Hamza417** [comment]
It's fixed now, you should see proper icons now in both modes and for Material 3 accent as well.
