### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [Hamza417/Peristyle#75]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7824568610

Did you build the apk in an environment without git?

**Comment by Hamza417** [comment]
No, it was built in the same environment as all the previous builds.

**Comment by linsui** [comment]
Then maybe AGP somehow can't work with your git. No idea. Can you disable the vcsInfo?

```gradle
    buildTypes {
        release {
           vcsInfo.include false
        }
    }
```

**Comment by Hamza417** [comment]
I have updated the APK file with the changes in the existing commit as well, could you run it again now?

**Comment by linsui** [comment]
The vcsInfo issue is fixed. https://gitlab.com/linsui/fdroiddata/-/jobs/7827543383 But it seems your apk is built from a different commit.

**Comment by Hamza417** [comment]
I found the problem, The Gradle missed a sync and built the APK based on recent dependencies. I'm uploading a new APK that should work.

**Comment by Hamza417** [comment]
Updated the APK, it should work now

**Comment by linsui** [comment]
It's not reproducible. I thought you need to cleanup the cache before build. :)

**Comment by Hamza417** [comment]
I built the APK again after invalidating all caches, maybe it'll work now. Could this be related to [this issue](https://github.com/Hamza417/Peristyle/issues/28)?

**Comment by linsui** [comment]
It's a common issue. It's fixed now, thanks! :)

**Comment by linsui** [comment]
2.03 failed... Can you clean the cache and rebuild the apk? :)

**Comment by linsui** [comment]
It's fixed, thanks!
