### ISSUE TITLE
App color scheme does not sync with system material you color pallete on fresh startup.

### ISSUE THREAD

**Issue by rickdtc** [Hamza417/Peristyle#8]
If I freshly start the app when it was not already open in the background before, it does not sync with system color palette.

This only happens with everything except settings page.

However, if I change color pallete while the app is open in the background, it syncs with the new color palette. 

https://github.com/Hamza417/Peristyle/assets/74096544/f66fd799-7b58-4693-ac65-13e91cd5ee28

**Comment by Hamza417** [comment]
Thanks, I couldn't have found this on my own. It's fixed now.

**Comment by rickdtc** [comment]
This is one of the cases where you can say both `thanks` and `you are welcome` at the same time lmao
