### ISSUE TITLE
Changes both lock and home screen

### ISSUE THREAD

**Issue by rigerc** [Hamza417/Peristyle#80]
Since 2.02b it changes both screen even though I've disabled it in settings.

Really appreciating all the changes in the app, looks like it's going to be great!

**Comment by Hamza417** [comment]
It's fixed now!

**Comment by rigerc** [comment]
Trying out the new version it doesn't seem to be fixed, my lock screen is still being changed... I also removed storage/cache for a fresh start ...

**Comment by Hamza417** [comment]
Should be fixed now this time
