### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ansarimohammed422** [Hamza417/Peristyle#9]
It just crashes when ever i tap on any wallpaper

I am on miui 14 android 13

This makes the spp completely useless

**Comment by ClockGen** [comment]
Hello, I planned to work on including this app to F-Droid (since you opened an RFP), however I experience this bug as well, the app just crashes after pressing anywhere on start screen.

Crash log is attached.
[crash.log](https://github.com/Hamza417/Peristyle/files/13950539/crash.log)

**Comment by Hamza417** [comment]
Thanks for the crash log, should be fixed now ;)
you can run it and let me know if it fixes it or not, i'll release an update then.

[app-prod-release.zip](https://github.com/Hamza417/Peristyle/files/13950642/app-prod-release.zip)

**Comment by Hamza417** [comment]
@ClockGen Is it crashing on main screen or wallpaper's?

**Comment by Hamza417** [comment]
[app-prod-release_02.zip](https://github.com/Hamza417/Peristyle/files/13953024/app-prod-release_02.zip)
Try this one, it crashes, send me the logs again.

**Comment by ClockGen** [comment]
It seems to work fine now.

**Comment by Hamza417** [comment]
Thanks, I'll publish a release now.
