### ISSUE TITLE
Wallpapers not updated

### ISSUE THREAD

**Issue by ansarimohammed422** [Hamza417/Peristyle#90]
I have 3115 wallpapers in my directory
But it is just stuck at 3059 and whenever i add more wallpapers it doesnt updates

**Comment by Hamza417** [comment]
It's fixed now.

**Comment by Hamza417** [comment]
![IMG_20241004_120222](https://github.com/user-attachments/assets/18fbcb82-1fef-455e-916f-74c10e2986c8)
 I have also added a loading indicator to show how much loading is left. That should make it convenient for loading large collections

**Comment by ansarimohammed422** [comment]
When will that fixed version release
