### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Hamza417/Peristyle#93]
Continuing from #68, today it's:

```
! repo/app.simple.peri_300.apk declares sensitive permission(s):
  android.permission.REQUEST_DELETE_PACKAGES android.permission.READ_MEDIA_IMAGES
```

Why would a wallpaper app want to uninstall apps I wonder? And as it worked without `READ_MEDIA_IMAGES` before, could you please clarify what this is needed for now? Thanks in advance!

**Comment by Hamza417** [comment]
It's been discussed in the Issue #72, and you can read the conclusion [here](https://github.com/Hamza417/Peristyle/issues/72#issuecomment-2357558761) about these permissions. As for `REQUEST_DELETE_PACKAGES` it is used to uninstall the live wallpapers from the [live wallpaper picker screen](https://github.com/Hamza417/Peristyle/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/02.png). It's wallpaper manager app, not wallpaper app, hence the permissions.

**Comment by IzzySoft** [comment]
Thanks @Hamza417! Both went to the app's "green list" now, together with the proper explanation for transparency.
